### ISSUE TITLE
UB_Uploader exceeds playfab limits and error with Virtual Currency Settings

### ISSUE THREAD

**Issue by rogerOlier** [PlayFab/UnicornBattle#10]
Hi!
First of all thanks for this fantastic and well documented example.

UB_Uploader exceeds limits of playfab : 
Current limit for title:
10,000 bytes (Default)

Recent values exceeding limit:
2016-07-13T08:09:30 UTC - 14,719 bytes

Also, Uploading Virtual Currency Settings fails.

Please see PreviousUploadLog.txt
Setting Destination TitleId to:****
Setting DeveloperSecretKey to:*********************************
Uploading Title Data Keys & Values...
	Uploading: Achievements
		Achievements Uploaded.
	Uploading: CharacterLevelRamp
		CharacterLevelRamp Uploaded.
	Uploading: Classes
		Classes Uploaded.
	Uploading: CommunityWebsite
		CommunityWebsite Uploaded.
	Uploading: DefaultBossCreeps
		DefaultBossCreeps Uploaded.
	Uploading: DefaultCreeps
		DefaultCreeps Uploaded.
	Uploading: DefaultHeroEncounters
		DefaultHeroEncounters Uploaded.
	Uploading: DefaultMegaCreeps
		DefaultMegaCreeps Uploaded.
	Uploading: DefaultRareCreeps
		DefaultRareCreeps Uploaded.
	Uploading: DefaultStoreEncounters
		DefaultStoreEncounters Uploaded.
	Uploading: Events
		Events Uploaded.
	Uploading: Levels
	 An error occured during: 		TitleData Upload: Levels
		[DataLengthExceeded] -- DataLengthExceeded:  
	Uploading: MinimumInterstitialWait
		MinimumInterstitialWait Uploaded.
	Uploading: Offers
		Offers Uploaded.
	Uploading: Sales
		Sales Uploaded.
	Uploading: Spells
		Spells Uploaded.
	Uploading: StandardStores
		StandardStores Uploaded.
	Uploading: StartingCharacterSlots
		StartingCharacterSlots Uploaded.
Uploading Virtual Currency Settings...
	 An error occured during: 	VC Upload Error: 
		[InvalidParams] -- Invalid input parameters: System.String[]
 
	An unexpected error occurred: 	Failed to upload Economy Data.
UB_Uploader.exe ended with errors. See PreviousUploadLog.txt for details

**Comment by zac-playfab** [comment]
Hey Roger, 
I am glad you are finding the example helpful. I believe our limits were initially conflicting with this example project. To my knowledge this has been resolved. I just ran the uploader against a new title with 0 issues.

Please let us know if you continue to run into issues.

-Zac
