### ISSUE TITLE
CDN content

### ISSUE THREAD

**Issue by ttermeer-ouat** [PlayFab/UnicornBattle#11]
The demo requires CDN content but it is a premium feature. Anyway to test without it ?

**Comment by pgilmorepf** [comment]
Yes.
The CDN is only used for Events.
If you navigate to TitleData:
https://developer.playfab.com/en-us/YOUR_TITLE_ID/content/title-data
and change this key:
ActiveEventKeys = "[]"
Then you won't have any active events, and thus the game won't try to access the CDN.

Let us know if you have any issues.
