### ISSUE TITLE
You leaked your devkey

### ISSUE THREAD

**Issue by KDSBest** [PlayFab/UnicornBattle#18]
https://github.com/PlayFab/UnicornBattle/blob/master/UnicornBattle/Assets/PlayFabSDK/Shared/Public/Resources/PlayFabSharedSettings.asset

<--- DevKey and TitleId is saved in there. You should put this file to gitignore and Revoke the key.

**Comment by KDSBest** [comment]
I made a test call to the api to see if the devkey really is leaked. Sadly the devkey is valid

**Comment by sdasfsfa** [comment]
How did you made the test call to the API. could you please give me the API call curl command or steps to reproduce?
