### ISSUE TITLE
Back end tool links are 404

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnicornBattle#5]
In [Readme.md](https://github.com/PlayFab/UnicornBattle/blob/master/README.md) and [Back-end guide](https://github.com/PlayFab/UnicornBattle/wiki/1-Unicorn-Battle-Backend-Guide) all links to UB_Uploader are 404.

They are not on master branch.

**Comment by zac-playfab** [comment]
Yep. Resolved now. Thanks!
